data_dir:        ./data
images_url:      https://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz
labels_url:      https://www.robots.ox.ac.uk/~vgg/data/flowers/102/imagelabels.mat
artifact_dir:    ./artifacts
best_model_name: best_model.pth

test_size:    0.15
val_size:     0.15
random_state: 42

batch_size:  16
num_workers: 2
image_size:  224

n_classes:  102
pretrained: true
freeze_backbone: false

num_epochs:    15
lr:            0.0005
weight_decay:  0.0001
lr_step_size:  5
lr_gamma:      0.5
